apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30001  # Optional: Define a specific NodePort
