apiVersion: v1
kind: Service
metadata:
  name: ping-pong-service
spec:
  type: NodePort
  selector:
    app: ping-pong
  ports:
    - name: python-port
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 31001
    - name: go-port
      protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 31002
