apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-go
  template:
    metadata:
      labels:
        app: ping-pong-go
    spec:
      containers:
      - name: ping-pong
        image: ping-pong-go:latest
        ports:
        - containerPort: 8081
