apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong
        image: sarikapt9/ping-pong-python
        ports:
        - containerPort: 8081
