apiVersion: v1
kind: Service
metadata:
  name: ping-pong-python
spec:
  type: NodePort
  selector:
    app: ping-pong
  ports:
  - protocol: TCP
    port: 8081          # Exposed service port
    targetPort: 8081    # Matches containerPort
    nodePort: 32183     # NodePort within 30000–32767
